name: Run Jupyter Notebook

on: [push]

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install notebook
          pip install kaggle
          pip install scikit-learn
          mkdir -p ~/.kaggle
          echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute MyKaggle1.ipynb --output executed_notebook.ipynb